### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by ctxcode** [Piggy-Loyalty/piggy-php-sdk#4]
Hi, tried using the package, but it seems to be broken, is this project still a work in progress?

```
Fatal error: Uncaught Error: Call to a member function getBody() on null in vendor/piggy/piggy-php-sdk/src/Exceptions/ExceptionMapper.php:23
Stack trace:
#0 vendor/piggy/piggy-php-sdk/src/Http/BaseClient.php(80): Piggy\Api\Exceptions\ExceptionMapper->map()
#1 vendor/piggy/piggy-php-sdk/src/Http/BaseClient.php(206): Piggy\Api\Http\BaseClient->request()
#2 app/classes/Piggy.php(18): Piggy\Api\Http\BaseClient->get()
```

my code:
```
class Piggy {

    private $client;

    public function __construct(\Shop $shop) {
        $clientId = $shop->settings->modules->piggy->client_id;
        $clientSecret = $shop->settings->modules->piggy->client_secret;
        $client = new Piggy\Api\OAuthClient($clientId, $clientSecret);
        $access_token = $client->getAccessToken();
        $client->setAccessToken($access_token);

        $this->client = $client;
    }

    public function getShops() {
        return $this->client->get('https://api.piggy.nl/api/v2/oauth/clients/api/v2/oauth/client/shops');
    }

}
```
Error when calling `getShops()`

**Comment by EdingerMike** [comment]
Hi @ctxkiwi ,

This project is currently in Beta, thank you for testing this package. We have fixed this bug and released version 0.0.7.

If you still encouter problems, please let me know.

**Comment by MV-ICT** [comment]
Hallo,

Ik probeer een GiftcardTransaction toe te voegen maar krijg bij alle kaarten de volgende foutmelding:
"{"code":1114,"status_code":400,"message":"The giftcard is upgradeable"}"
Bij kaarten welke opwaardeerbaar zijn en bij kaarten welke niet opwaardeerbaar zijn. Ook bij een negatief bedrag.
